export enum StatusMesa {
    LIVRE = "LIVRE",
    OCUPADA = "OCUPADA",
    EM_FECHAMENTO = "EM_FECHAMENTO",
    AGUARDANDO_LIMPEZA = "AGUARDANDO_LIMPEZA",
    RESERVADA = "RESERVADA",
    BLOQUEADA = "BLOQUEADA",
}
